[:h2 "Installation"]
[:p "Installing Joodo is as easy as your favorite pie (eating, not baking): all you need is Leiningen and the Joodo plugin. Follow the " [:a {:href "https://github.com/technomancy/leiningen/blob/master/README.md" :target "_blank"} "latest tutorial"] " on Leiningen's github account to acquire the latest version, then visit your terminal to install the Joodo plugin:"]
[:code "joodo/lein-joodo 0.6.0-SNAPSHOT"]
[:p "When that finishes the Joodo command will get installed on your system in the '~/.lein/bin/' directory. If '~/.lein/bin/' is already apart of your '$PATH', then you can use Joodo now. If it isn't, you can add it to your path by running the following command:"]
[:code "export PATH=$PATH:~/.lein/bin"]
[:p "For changes in your path file to be applied, you must restart your terminal."]