[:h2 "why joodo?"]
[:p "Building websites and web applications with Joodo is an extremely easy process. Joodo does this by integrating " [:a {:href "https://github.com/mmcgrana/ring" :target "_blank"} "Ring"] ", " [:a {:href "https://github.com/weavejester/compojure" :target "_blank"} "Compojure"] ", " [:a {:href "https://github.com/weavejester/hiccup" :target "_blank"} "Hiccup"] ", " [:a {:href "https://github.com/slagyr/speclj" :target "_blank"} "Speclj"] ", and " [:a {:href "https://github.com/technomancy/leiningen" :target "_blank"} "Leiningen"] ". If you are unfamiliar with any of those technologies don't worry, they were picked because of their power and ease of use. Installing Joodo can be done by running a few commands in the terminal, and creating and deploying projects are just as easy."]

[:h1 "This is an h1"]
[:p "The 'joodo' command will be installed on your system in the '~/.lein/bin/' directory. Next, edit the '.profile' (found in your home directory) to include '$HOME/.lein/bin/' in your path. Run the following in your terminal:"]
[:h1 "This is an h1"]
[:h3 "This is an h3"]
[:p "The 'joodo' command will be installed on your system in the '~/.lein/bin/' directory. Next, edit the '.profile' (found in your home directory) to include '$HOME/.lein/bin/' in your path. Run the following in your terminal:"]

[:h2 "This is an h2"]
[:p "The 'joodo' command will be installed on your system in the '~/.lein/bin/' directory. Next, edit the '.profile' (found in your home directory) to include '$HOME/.lein/bin/' in your path. Run the following in your terminal:"]
[:h2 "This is an h2"]
[:h3 "This is an h3"]
[:p "The 'joodo' command will be installed on your system in the '~/.lein/bin/' directory. Next, edit the '.profile' (found in your home directory) to include '$HOME/.lein/bin/' in your path. Run the following in your terminal:"]
[:h4 "This is an h4"]
[:p "The 'joodo' command will be installed on your system in the '~/.lein/bin/' directory. Next, edit the '.profile' (found in your home directory) to include '$HOME/.lein/bin/' in your path. Run the following in your terminal:"]
[:p "Building websites and web applications with Joodo is an extremely easy process. Joodo does this by integrating " [:a {:href "https://github.com/mmcgrana/ring" :target "_blank"} "Ring"] ", " [:a {:href "https://github.com/weavejester/compojure" :target "_blank"} "Compojure"] ", " [:a {:href "https://github.com/weavejester/hiccup" :target "_blank"} "Hiccup"] ", " [:a {:href "https://github.com/slagyr/speclj" :target "_blank"} "Speclj"] ", and " [:a {:href "https://github.com/technomancy/leiningen" :target "_blank"} "Leiningen"] ". If you are unfamiliar with any of those technologies don't worry, they were picked because of their power and ease of use. Installing Joodo can be done by running a few commands in the terminal, and creating and deploying projects are just as easy."]
[:code "export PATH=$PATH:~/.lein/bin"]
[:p "The 'joodo' command will be installed on your system in the '~/.lein/bin/' directory. Next, edit the '.profile' (found in your home directory) to include '$HOME/.lein/bin/' in your path. Run the following in your terminal:"]
